services:

  postgres:
    image: postgres:17.2-alpine3.21
    restart: always
    command: postgres -c 'max_connections=250'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    volumes:
      - ./init-postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"